# Generated by Django 3.0.4 on 2020-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_auto_20200410_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=10)),
                ('name', models.CharField(default='Admin', max_length=30)),
                ('head_text', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
