# Generated by Django 3.0.4 on 2020-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_auto_20200410_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enproduct',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ruproduct',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
